util = require './util'

elems = [
  "I am a strange loop.",
  "The Art of Computer Programming",
  "Basic Computer Games",
  "The Soul of a New Machine",
  "Inside the IBM PC",
  "Heroes of the Computer Revolution",
  "Fire in the Valley",
  "The New Hacker's Dictionary",
  "Accidental Empires",
  "The Cathedral and the Bazaar",
  "I am a strange loop.",
  "The Art of Computer Programming",
  "Basic Computer Games",
  "The Soul of a New Machine",
  "Inside the IBM PC",
  "Heroes of the Computer Revolution",
  "Fire in the Valley",
  "The New Hacker's Dictionary",
  "Accidental Empires",
  "The Cathedral and the Bazaar",
  "I am a strange loop.",
  "The Art of Computer Programming",
  "Basic Computer Games",
  "The Soul of a New Machine",
  "Inside the IBM PC",
  "Heroes of the Computer Revolution",
  "Fire in the Valley",
  "The New Hacker's Dictionary",
  "Accidental Empires",
  "The Cathedral and the Bazaar",
  "I am a strange loop.",
  "The Art of Computer Programming",
  "Basic Computer Games",
  "The Soul of a New Machine",
  "Inside the IBM PC",
  "Heroes of the Computer Revolution",
  "Fire in the Valley",
  "The New Hacker's Dictionary",
  "Accidental Empires",
  "The Cathedral and the Bazaar",
  "I am a strange loop.",
  "The Art of Computer Programming",
  "Basic Computer Games",
  "The Soul of a New Machine",
  "Inside the IBM PC",
  "Heroes of the Computer Revolution",
  "Fire in the Valley",
  "The New Hacker's Dictionary",
  "Accidental Empires",
  "The Cathedral and the Bazaar"
]

t = new util.AESHexTranslator('50db7d7ce3dd17af01c43c94825deed6c65eccf84fb1d9f5b3f2830b238c715a')

for elem in elems
  util.Log(t.generateDbElem(elem,{'l': 512}))
